<?php if (!defined('BUDDY_PATH')) exit();?><html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><title><?php echo C("SITE.title");?> MIS系统</title><script type="text/javascript" src="<?php if(isset($page["resurl"])) { echo ($page["resurl"]); }  ?>/js/jquery.min.js"></script><link href="<?php if(isset($page["resurl"])) { echo ($page["resurl"]); }  ?>/images/misimages/main.css" rel="stylesheet" type="text/css"/><script type="text/javascript" src="<?php if(isset($page["resurl"])) { echo ($page["resurl"]); }  ?>/images/misimages/common.js"></script></head><body><div><div class="handle-btns"><div class="img-button"><p><input type="button" id="addAdmin" name="addAdmin" value="添加"
					onclick="addData()" class="addAdmin"></p></div><div class="img-button "><p><input type="button" id="editAdmin" name="editAdmin" value="编辑"
					onclick="editData(this,'checkList','uid')" class="editAdmin"></p></div><div class="img-button "><p><input type="button" id="removeAdmin" name="removeAdmin" value="删除"
					onclick="removeData(this,'checkList')" class="removeAdmin"></p></div><form name="form1" action="<?php echo U('search/object');?>" method="post"><span>对象</span><select name="object"><option value="">所有会员</option><option value="1">前台管理员</option><option value="2">分享管理员</option><option value="3">论坛管理员</option><option value="4">问答管理员</option><option value="5">闲置管理员</option></select><span>内容</span><input class="textinput" type="text" value=""
		name="content" size="10" style="margin-top: 5px;"><input
		class="submit_btn" type="submit" value="搜索"></form></div><table id="checkList" class="table-list list" cellpadding="0"
		cellspacing="0" border="0"><thead><tr><th width="30" class="first"><input type="checkbox"
					onclick="checkAll('checkList')"></th><th width="130">ID				</th><th width="360">内容
				</th><th width="120">创建用户</th><th width="120">对象ID</th><th width="60">状态</th><th width="60">类型</th><th width="60">回复</th><th width="60">转发</th><th width="80">操作</th></tr></thead><tbody><?php if(isset($page['data']['post']) && is_array($page['data']['post'])){ $i = 0; $__LIST__ = $page['data']['post'];if( count($__LIST__)==0 ) { echo "" ; }else{ foreach($__LIST__ as $key=>$vo){ ++$i;$mod = ($i % 2 );?><tr class="even" id="obj_<?php if(isset($vo["id"])) { echo ($vo["id"]); }  ?>"><td class="first"><input type="checkbox" name="key" value="<?php if(isset($vo["id"])) { echo ($vo["id"]); }  ?>"></td><td><?php if(isset($vo["id"])) { echo ($vo["id"]); }  ?></td><td align="left"><?php if(isset($vo["content"])) { echo ($vo["content"]); }  ?></td><td align="left"><?php if(isset($vo["account_id"])) { echo ($vo["account_id"]); }  ?></td><td><?php if(isset($vo["object_id"])) { echo ($vo["object_id"]); }  ?></td><td><?php if($vo['status'] == 0) { ?>启用
					<?php }else{ ?><font color="red">禁用</font><?php } ?></td><td><?php if(isset($vo["action"])) { echo ($vo["action"]); }  ?></td><td><?php if(isset($vo["reply"])) { echo ($vo["reply"]); }  ?></td><td><?php if(isset($vo["usercopy"])) { echo ($vo["usercopy"]); }  ?></td><td><a href="">编辑</a>&nbsp;&nbsp;<a href="javascript:;" onclick="delobj('<?php if(isset($vo["id"])) { echo ($vo["id"]); }  ?>')">删除</a>&nbsp;&nbsp;</td></tr><?php } } } ?></tbody></table><div class="clear"></div><div class="paginator"><?php  echo (page($page['data']['count'],$page['data']['size']));  ?></div></div></body></html>